version: '3.7'

services:
  typescript:
    image: discord-subcom-bot/typescript
    container_name: discord-subcom-bot_typescript
    build: .

  postgres:
    image: postgres
    container_name: discord-subcom-bot_postgres
    environment:
      POSTGRES_PASSWORD: app
      POSTGRES_USER: app
      POSTGRES_DB: db
    volumes:
    - ./db/:/var/lib/postgresql/data
    ports:
    - 1060:5432